### ISSUE TITLE
Error in PopInvokedWithResultCallback in latest version

### ISSUE THREAD

**Issue by nooralinakheel** [mono0926/adaptive_dialog#135]
After updating to latest version 2.2.0 I am getting following error:

```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           24.8s
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/modal_action_sheet/modal_action_sheet.dart:27:3: Error: Type 'PopInvokedWithResultCallback' not found.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

I tried cleaning, tried deleting the pub cache but nothing is working. So I moved back 1 version 2.1.0 and that works.

**Comment by mono0926** [comment]
@nooralinakheel 

The API is for Flutter 3.24 and later, so that error occurs in earlier versions. The `adaptive_dialog` required a specification in pubspec.yaml for Flutter 3.24 and later, but it was missing, so I corrected that and released version 2.2.1. 

If you are using a version earlier than Flutter 3.24, please specify `adaptive_dialog: 2.1.0` to resolve the issue.

Refer to this: https://pub.dev/packages/adaptive_dialog/changelog#220
