### ISSUE TITLE
Request : is it possible to dim the backgroud

### ISSUE THREAD

**Issue by mohadel92** [mono0926/adaptive_dialog#37]
in the normal dialog i can wrap it with BackdropFilter so that i can have  a dimmer background when calling the dialog?

**Comment by mono0926** [comment]
Could you paste an image of it?

**Comment by mohadel92** [comment]
@mono0926 thank you for your response
i would like to add this feature if possible
i am only wrapping it in a BAckfilter
<a href="https://ibb.co/H2Kq2bm"><img src="https://i.ibb.co/mBR4B2Q/Simulator-Screen-Shot-i-Phone-12-Pro-Max-2021-06-14-at-11-04-37.png" alt="Simulator-Screen-Shot-i-Phone-12-Pro-Max-2021-06-14-at-11-04-37" border="0"></a>

**Comment by mono0926** [comment]
@mohadel92 

Thanks for the image.

It can be implemented, but I don't support it because this package follows this standard design guideline. Blurred effect doesn't match it.

- [Alerts - Views - iOS - Human Interface Guidelines - Apple Developer](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/)
- [Dialogs - Material Design](https://material.io/components/dialogs)

**Comment by mohadel92** [comment]
okay a really good reply ,
but only dimming without blur @mono0926 ??
is it possible

**Comment by mono0926** [comment]
@mohadel92 

adaptive_dialog dims background already as the screenshots here: https://github.com/mono0926/adaptive_dialog#showokalertdialog

It can be adjusted yourself, but adaptive_dialog doesn't support that kind of flexibility.
